### ISSUE TITLE
Προσθήκη  ελέγχου φακέλου και αν δεν υπάρχει να τον δημιουργεί

### ISSUE THREAD

**Issue by gkanos** [JohnGavr/ytd101#3]
Κοιτάζοντας τον κώδικα, παρατήρησα οτι αν διαβάσεις το αρχείο με τον φακέλο που θα γίνουν extract τα αρχεία αλλα δεν υπάρχει έλεγχος για την ύπαρξη του φακέλου ωστε να δημιουργηθεί. 

Προκαλώντας θέμα στο που θα γίνουν extract τα αρχεία αν ο φάκελος δεν υπάρχει. Οπότε ενας έλεγχος για την ύπαρξη και δημιουργία του φακέλου θα βοηθούσε.

Παράδειγμα για αναπαραγωγή προβλήματος:
Αλλάγή του φακέλου στο αρχείο από music -> music_mp3_downloaded

**Comment by JohnGavr** [comment]
Ευχαριστώ για την παρατήρηση.
Έχω κάνει ένα commit στο develop branch. Περιμένω νέα μέχρι να εισαχθεί στο master.
